# Generated by Django 5.0.4 on 2024-05-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('date1', models.CharField(blank=True, max_length=30, null=True)),
                ('date2', models.CharField(blank=True, max_length=30, null=True)),
                ('profession', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('photo', models.CharField(blank=True, max_length=30, null=True)),
                ('wiki', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
